# Generated by Django 4.2.6 on 2023-11-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
        ('learning_activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='learning_topics',
            field=models.ManyToManyField(blank=True, related_name='research_topic', to='root.learningtopics'),
        ),
    ]
