# Generated by Django 4.2.6 on 2023-11-08 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning_activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='researchpaper',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='research_paper_tags', to='root.tags'),
        ),
        migrations.AddField(
            model_name='progsql',
            name='learning_topics',
            field=models.ManyToManyField(blank=True, related_name='sql_topic', to='root.learningtopics'),
        ),
        migrations.AddField(
            model_name='progsql',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progsql',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='sql_tags', to='root.tags'),
        ),
        migrations.AddField(
            model_name='progdsa',
            name='learning_topics',
            field=models.ManyToManyField(blank=True, related_name='dsa_topic', to='root.learningtopics'),
        ),
        migrations.AddField(
            model_name='progdsa',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='progdsa',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dsa_tags', to='root.tags'),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='learning_topics',
            field=models.ManyToManyField(blank=True, related_name='interview_topic', to='root.learningtopics'),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mock_interview_tags', to='root.tags'),
        ),
    ]
