# Generated by Django 4.2.6 on 2023-12-09 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalurl",
            name="external_provider",
        ),
        migrations.RemoveField(
            model_name="externalurl",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="external_provider",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="resource",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="resource",
        ),
        migrations.DeleteModel(
            name="ExternalDataProvider",
        ),
        migrations.DeleteModel(
            name="ExternalUrl",
        ),
        migrations.DeleteModel(
            name="Metric",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
