# Generated by Django 4.2.6 on 2023-12-09 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_externalurl_external_provider_and_more"),
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="resource_ptr",
        ),
        migrations.RemoveField(
            model_name="video",
            name="course_instance",
        ),
        migrations.RemoveField(
            model_name="video",
            name="resource_ptr",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="Resource",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
